services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: always
    networks:
      - nginx
    volumes:
      - ./config:/var/www/baikal/config
      - ./data:/var/www/baikal/Specific

networks:
  nginx:
    external: true
    name: nginx
  local: